directories:
  output: public
  buildResources: build
appId: com.richardkriesman.socketfox
appImage:
  category: Development
  synopsis: 'Develop better, faster websockets in Socket.IO.'
linux:
  icon: build/icon.icns
  publish:
    provider: generic
    url: 'https://socketfox.richardkriesman.com'
    channel: latest
  target: AppImage
mac:
  publish:
    provider: generic
    url: 'https://socketfox.richardkriesman.com'
    channel: latest
electronVersion: 2.0.5
